### PR TITLE
Somfy Tahoma plugin

### PR DESCRIPTION
**Pull request by msbg**
Hi,
Many thanks for creating this bridge - it works beautifully in our Alexa'd house.  I've added a plugin to support devices that can be controlled from a Somfy Tahoma box (this allows communication over IO-Homecontrol which is the protocol used by Velux windows and blinds).  Only caveat is I have to ask 'turn on bathroom window' to open it:)
This is my first pull request on GitHub, so apologies if I've gone against convention in any way.  

Many thanks,

- monica

### CODE REVIEW

**Comment by bwssytems** [comment]
Cool! Thanks will be pulling in for the next release.

**Comment by bwssytems** [comment]
Taking a very, very quick look, I see that you are creating another HTTP client. I was trying to always use the HTTPHandler for this as to not have multiple places for http client code. What are your thoughts?

**Comment by msbg** [comment]
Good plan - updated accordingly.  Thanks for the feedback,

- monica

**Comment by bwssytems** [comment]
Did some review here, so for the JSON usage when getting the info, it would be best just to have a pojo with only the fields that are needed to extract that information. This becomes unwieldy if the interface changes from Somfy.

**Comment by msbg** [comment]
Meged to latest master and cleaned up the json->pojo mappings as suggested - thanks!

- monica

**Comment by bwssytems** [comment]
Yes, that looks much better. I assume you have the Somfy blinds and testing works as expected. I will merge this in and then put it in the next release.

**Pull request merged**
