### PR TITLE
Logout request and Shutdown hook

### PR DESCRIPTION
**Pull request by gaudryc**
Hi !

Because authenticated user sessions are never cleaned, I think it would be a good idea, for security reasons, to invalidate the session each time a user logged out.

You can see that I didn't break the manner you use of "auth.logout" method.

Thanks in advance.

Chris

### CODE REVIEW

**Comment by gaudryc** [comment]
With shutdown hook,  you can be able to properly stop or restart HA-Bridge from the command line.
It also allows the host machine to properly stop HA-Bridge before shutting down.

**Comment by bwssytems** [comment]
Thanks, will review

**Comment by bwssytems** [comment]
This looks great! Thanks for finding a bunch of issues and code updates that are bad form from my end. Will put in the next release.

**Comment by gaudryc** [comment]
Thank you and you're welcome.
I will wait impatiently for the next version or beta and I will probably do
a static code checking pass and submit some very small bug fixes detected
in January.

**Pull request merged**
