### PR TITLE
Add Fritzbox Smarthome support

### PR DESCRIPTION
**Pull request by alias**
This can control the DECT ULP connected power switches or heater controllers through an AVM Fritzbox.

### CODE REVIEW

**Comment by bwssytems** [comment]
Awesome, Thanks!

**Comment by bwssytems** [comment]
Simple review, so is there a way to get a list of devices to create the UI builder?

**Comment by alias** [comment]
probably yes; do you have an example how that looks like, or can I see that UI Builder somewhere?

**Comment by bwssytems** [comment]
yes, looking at HASS or Domoticz implementations would be best.

**Comment by alias** [comment]
where can I see this code in action? Is there a button that shows up or so? Its hard to imagine without even any interface documentation ;-) Its probably not enough to just implement the ResourceHandler interface (what is the "type" there?)

**Comment by alias** [comment]
updated for 5.1.  No patience to implement alle the parts, sorry

**Comment by bwssytems** [comment]
Cancelling this pull request as Mozilla IOT supports Fritz!

https://iot.mozilla.org

**Pull request closed without merging**
