### PR TITLE
Make LOCATION header use a reasonable IP in UPNP responses

### PR DESCRIPTION
**Pull request by pvint**
See Issue #980 

The LOCATION header in UPNP replies can be set to the wrong IP when you have `useUpnpIface: false` set. and you have multiple IP addresses. 

Example:

```
U 192.168.1.73:1900 -> 192.168.1.75:50000
HTTP/1.1 200 OK.
HOST: 239.255.255.250:1900.
CACHE-CONTROL: max-age=100.
EXT:.
LOCATION: http://10.36.12.186:8088/description.xml.
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0.
hue-bridgeid: 000088FFFE00BBEE.
ST: uuid:2f402f80-da50-11e1-9b23-00008800bbee.
USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee.
.
```

It appears that it will always reply on the appropriate interface, however when setting the LOCATION header it simply uses the IP of the last interface that it found (which in my case was the tun0 interface which cannot work).

After this change, it works and devices can be discovered:

```
U 192.168.1.73:1900 -> 192.168.1.75:50000
HTTP/1.1 200 OK.
HOST: 239.255.255.250:1900.
CACHE-CONTROL: max-age=100.
EXT:.
LOCATION: http://192.168.1.73:8088/description.xml.
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.19.0.
hue-bridgeid: 000088FFFE00BBEE.
ST: uuid:2f402f80-da50-11e1-9b23-00008800bbee.
USN: uuid:2f402f80-da50-11e1-9b23-00008800bbee.
```

### CODE REVIEW

**Comment by bwssytems** [comment]
Thanks, will take a look.

**Comment by bwssytems** [comment]
Now that I take a look at this, I try to do this in the setup of bridge settings. If there is no upnp config address, I try to find one by looping through the interfaces and picking a valid ipv4 addr. Since the http address is always defaulted to 0.0.0.0 on start up, this usually is not an issue.

**Comment by pvint** [comment]
Good stuff, thanks!

I honestly couldn't come up with another way to determine the address the upnp request came from, but I would definitely welcome a cleaner way to do it.

FWIW, I've been using this with my patch on two completely different systems (both of which had the same issue previously), and it's working fine.

I'll continue using mine for now, but if you come up with another way I'll be happy to test it.

**Comment by bwssytems** [comment]
I was thinking of building a route matcher by requesting ip to interface ip, that works be the other way, for now, your trick will work

**Comment by pvint** [comment]
I took a look at that, and yes, that may be a better way to go. It conceivably still could be wrong in the event that you have more than one IP on the same subnet, but that would be a relatively rare case (and also would imply static IP addresses, in which case you could set the upnp address explicitly)

I may test this idea, but it will likely be a while before I really have time.

**Comment by bwssytems** [comment]
Thanks, I may start looking into the code for this relatively soon.

**Comment by bwssytems** [comment]
In the end I added your version with a correction which was to let it resolve addresses as your version in testing gave unresolved address exceptions. This is in 5.2.2RC now.

**Comment by bwssytems** [comment]
Closing this pull request

**Pull request closed without merging**
