### PR TITLE
Room and basic color support and some minor stuff

### PR DESCRIPTION
**Pull request by FloFoer**
Maybe you are interested in that.  

I implemented full api support for rooms. That means:  
- Create/Modify/Delete rooms/lightgroups  
When creating rooms with the hue app "Add default scenes" must always be unchecked in order for it to work correctly.
- Get information about group list / individual group, including "Group 0".
- Group actions: Change lighting for the whole group (no scenes, only on/off/dim and color for real hue lights, in the future color for custom devices)
Note that group actions iterate over all lights in that group, so if one url takes long to execute this is very noticeable.   

I tried for everything to give a good response similar to the real hue bridge.  
For now the rooms can only be configured through the api and apps, it's not visible/changeable through the web gui. I also removed the default room so one has to create one himself, like with every new hue bridge.  

The rooms are getting saved in a "group.db" which is stored at the specified data location. Path can be specified in bridge control below the device.db path.

I tried it with the official hue app and "all 4 hue" and with manual api calls, seems to work. Of course i will test it further.

I also did some minor stuff as described in the commit messages including:
- A ColorUrl additional to on/off/dim which gets executed when a color command arrives for that device 
- Possibility to change the "edit mode" during device edit to manual json input for the urls instead of the table thing for better copy/paste, insertion and reordering capabilities
- Filter in device list with: show only devices that are visible to a given ip-address

Edit: What i've done regarding color support can be found in the [commit comment](https://github.com/bwssytems/ha-bridge/pull/712/commits/8831fec6bef0671c6e45943143a3e7765231155e)

### CODE REVIEW

**Comment by bwssytems** [comment]
Great work! Just took a quick code review.

So, for groups, you have class types that do not seem to be types that the HUE API would give, they seem more like group names. Here is a snippet of the HUE API that I refer to:

```
1. Groups in Hue
The hue system has a notion of groups. Grouping of lights can be useful to execute a command for the set of lights within a group. The advantage of using group commands is that you will get a synchronous change of state of the lights within that group, and in the process, eliminate popcorn effect.

To change the state of the lights part of a group, use a PUT on the action endpoint:

/api/<username>/groups/<id>/action

For a description of all the possible actions, please visit:

http://www.developers.meethue.com/documentation/groups-api#25_set_group_state

It is possible to change the color of all lights in a group, or to recall a scene for that group.

A group can consists of different type of lights, and a light will perform the action which will fall within its capabilities, e.g. a “Dimmable Light” will not change in case the group command asks for a “xy” color change.

The hue system has the following types of groups:

LightGroup (group 0 is a special group, i.e. all lights)
Luminaire (created by bridge)
LightSource (created by bridge)
Room (with additional Class specifications)
All detailed, and latest updated, information about groups and the actions on groups can be found back in the description of the API:

http://www.developers.meethue.com/documentation/groups-api

Take into account:

maximum number of groups is 64
LightGroup 0 is a special group created by the bridge. All lights in the system are part of the LightGroup 0. This group can not be created, modified or deleted using the API.
“Luminaire” and “LightSource” are specific groups which are created automatically by the hue bridge, and can not be created, modified or deleted using the API. These groups are created as soon a multi-source luminaire is added to the hue system, e.g. hue Beyond.
As soon a “LightGroup” is empty, it will automatically be deleted from the bridge.
Rooms are specific, in that a lightpoint can not be present in mutiple “Rooms”. And a “room” is not automatically deleted when it is empty.
A scene action will only have impact on the light which are part of that group AND that are part of the lights within the scene.  A scene action for LightGroup 0 will have impact on lights part of the scene.
A light cannot have its hue, saturation, brightness, effect, ct or xy modified when it is turned off.
There are 3 methods available to set the color of the light – hue and saturation (hs), xy or color temperature (ct). If multiple methods are used then a priority is used: xy > ct > hs. All included parameters will be updated but the ‘colormode’ will be set using the priority system.
In case your application makes use of a room-based approach to control IoT devices in the home, it is best to re-use the rooms created using hue app gen 2.
```

**Comment by bwssytems** [comment]
Great work! Doing a code review. Deleted my comment about group types as I found it in the group api page.

**Comment by bwssytems** [comment]
Looks like you changed the scrollable table to be off. IT seems to have broken the sorting. I am making some changes so I will fix that. Other wise this looks good. Thanks!

**Comment by FloFoer** [comment]
Oh sorry, forgot that these changes where in there, should have excluded that.  
I did these changes intentional for myself. Wanted it always sorted by name and without the height constraint on the table, because i liked it more if i see everything instead of that small height.

inside scrollable-table.css i removed the fixed 310px height for .scrollableContainer
in the configuration.html in the ng-repeat for the device list is a constant orderBy:'Name' 

These should be the only changes in that "personal" way.
Except for maybe the column min/max widths in editeevice.html as commented in this [issue](https://github.com/bwssytems/ha-bridge/issues/381). Not sure if this is good for everyone.

**Comment by FloFoer** [comment]
Removing the height property was satisfying enough for me. I want to use my entire screen and not a small portion of it and i prefer scrolling with the main scrollbar and not in multiple separate boxes (like in editdevice with fixed height for the scrolltable)

Adding the orderBy:'Name' does sort my list by name from A-Z for me, but it disables the sorting function of the scrolltable. Would be better if we could somehow access the current sorting of the table and modify it. Or if the table would always remember the last sorting, even for new tabs. (But i wasn't so keen for that to actually invest more time, so i did this simple "fix" for me)

**Comment by bwssytems** [comment]
Yeah, definitely a default sort would be great. I have a request for that to the author of that table, but it is not going anywhere. Maybe I will fork it and fix it.

**Comment by bwssytems** [comment]
So, we have an issue. There is a piece of code that is breaking people's setups in the HueMulator changeState method. It is the if statement that checks for lightIds that are greater than 10000. I believe that is not needed any more. Comments?

**Comment by FloFoer** [comment]
This has somethting to do with rooms/groups regarding Alexa. 
I did implement the full room functionality, you can create rooms in the hue app, assign lights to it and execute all the room stuff which works just fine with apps. 
However, i discovered that Rooms are handled via the hue skill in alexa, so it will not discover HA-Bridge Rooms on its own. 
The thing with lightid > 10000 was a workaround i did in [this commit](https://github.com/bwssytems/ha-bridge/commit/95c342b5484e71c9430973d9d2267f4e00eb0d27) to get my rooms into Alexa. 
It applied the following logic: If someone requested the lights list it appends all rooms for which this is enabled as additional fake lights with light id 10000 + groupid. If one tries a GET or PUT to a light or its state with lightid > 10000 then it's assumed that a room is meant and extracts the corresponding groupid and continues with that. 
This feature has to be enabled for every room by editing the group.db entry with "exposeAsLight":"echo-ip-address" (Since there is no web ui for group editing). 
I assumed that lightids are assigned automatically and continuously, so that it should be impossible for real lights with such lightids to exist. Apparently this assumption was wrong?

**Comment by bwssytems** [comment]
The unfortunate thing is, before I changed the numbering, they were random and above 10000. So people are having issues with that.

**Comment by FloFoer** [comment]
Ok, didn't knew that. I based my assumption on the current tech state. So we either have to undo these code changes if this is to big of a problem or tell everyone to renumber their devices for compatibility with v5.

**Comment by bwssytems** [comment]
How about we put in a setting to use groups and if you do, you will have to renumber of ids area above 10000.

**Comment by FloFoer** [comment]
Yes this would be a possibility. Per default turned off. I would name this setting something like "Enable rooms for Alexa" or something like that, since rooms in general do function without that lightid > 10000 stuff, so no reason to turn that off. It's only necessary if you want to enable a room to be visible for Alexa.

**Comment by bwssytems** [comment]
I think this will be needed as people really have a lot of device they carried forward overtime and trying to keep this backward compatible.

**Comment by FloFoer** [comment]
@bwssytems 
I saw that you started to implement the "Enable rooms for Alexa" setting. 
I also saw that you applied the setting to everything group related. This is not really necessary since the problematic id > 10000 stuff is not needed for the entire rooms feature. Rooms with apps work just fine, the id > 10000 stuff is only a workaround to get the rooms displayed in Alexa without the skill.  That's the reason why i suggested the name "Enable rooms for alexa" and not just "Enable rooms". 

Also, if you apply the setting to everything group related you would have to provide all lights in a default group - like it was before - in order for habridge to be usable with apps (otherwise you would get a blank screen). I might be wrong but i think i haven't seen that in your recent changes?

I would suggest to only toggle the alexa workaround related stuff with this setting (this means everything where 10000 is mentioned) and to keep the rooms feature itself intact.

**Comment by FloFoer** [comment]
That's interesting. Do you mean this?  
```
if (path.endsWith("/")) { // it should work with or without a trailing slash
    response.redirect(path.substring(0, path.length() - 1)); 
}
```
If I remember correctly I added this because without it some apps I tried didn't work (not the official hue app though) because they called it with a trailing slash and habridge didn't  know what to do with it.

**Comment by bwssytems** [comment]
Yeah, that is it. What calls are you having issues with?

**Pull request merged**
