### PR TITLE
Added a optional webhook for harmony-activity changes

### PR DESCRIPTION
**Pull request by CrEaK**
Hey,
i needed a webhook-call when the harmony-activity changes, so I implemented it. Everytime the HarmonyListener gets a activity-change the webhook-url is called.
I outsourced the HTTPClient for the request to avoid duplicate code :)

Perhaps the features is interesting for others too?
Best regards!

### CODE REVIEW

**Comment by bwssytems** [comment]
That is pretty cool. Will look at putting this in

**Comment by CrEaK** [comment]
Nice :) Take your time and im open for any improvement suggestion 👍

**Comment by CrEaK** [comment]
added a NPE-Check for the webhook

**Comment by bwssytems** [comment]
So, with all of my refactoring for 4.0.0, this will need to rebase when that branch is tested.

**Comment by CrEaK** [comment]
Okay no problem, what can I do to help?

**Comment by bwssytems** [comment]
Let's wait until I get the V4 stable then we can rebase this in.

**Comment by bwssytems** [comment]
Alrigthy, version 4.0.0 is now on the master branch, take a look.

**Comment by CrEaK** [comment]
Sorry for taking so long :) I found the time to look at the changes and merged with master branch. Can you take a look? Thanks!

**Comment by bwssytems** [comment]
Thanks, will take a look

**Comment by bwssytems** [comment]
Will test this after the 4.2.1 release.

**Comment by CrEaK** [comment]
Alright 👍

**Pull request merged**
